routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\IndexController::class, 'main'])->name('main');
Route::get('/certainNews/{id}', [App\Http\Controllers\IndexController::class, 'certainNews'])->name('certainNews');

Auth::routes();



Route::prefix('adm')->group(function () {

    Route::get('/', [App\Http\Controllers\AdminController::class, 'admin'])->name('admin');

    Route::resource('/news', App\Http\Controllers\PostController::class);

});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'text',
        'image',
        'user_id',
    ];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function admin(){

        return view("admin/main");
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\News;

class IndexController extends Controller
{
    //

    public function main(){

        $news = News::paginate(150);

        return view('main',compact('news'));
    }

    public function certainNews($id){

        $news =News::findOrFail($id);

        return view('certainNews',compact('news'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::paginate(150);
        //
       return view("admin/news",compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //



        return  view("admin/newsAdd");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'text' => 'required',
        ]);

        $input = $request->all();

        if ($image = $request->file('image')) {

            $date = date("Y-m",time());
            $path = 'photo/'.$date;
            $gall = rand() . '.' .$image->getClientOriginalExtension();

            $image->move(public_path($path), $gall);

            $gall_new_name = $path."/".$gall;
            $catImg =  $gall_new_name;
            $imgc = Image::make(public_path($gall_new_name));
            $imgc->fit(350,350);
            $imgc->save();

            $input['image'] = $catImg;
        }
        $input['user_id'] = Auth::user()->id;


        News::create($input);


        return redirect()->route('news.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {

        return  view("admin/newsEdit",compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        $request->validate([
            'title' => 'required',
            'text' => 'required',
        ]);


        $input = $request->all();

        if ($image = $request->file('image')) {

            $date = date("Y-m",time());
            $path = 'photo/'.$date;
            $gall = rand() . '.' .$image->getClientOriginalExtension();

            $image->move(public_path($path), $gall);

            $gall_new_name = $path."/".$gall;
            $catImg =  $gall_new_name;
            $imgc = Image::make(public_path($gall_new_name));
            $imgc->fit(350,350);
            $imgc->save();

            $input['image'] = $catImg;
        }
        $input['user_id'] = Auth::user()->id;


        $news->update($input);

        return redirect()->route('news.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        $news->delete();

        return redirect()->route('news.index');
    }
}

resources/views/admin/main.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        test
    </div>
</div>
@endsection

resources/views/admin/news.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <a href="{{route('news.create')}}">
                <button type="button" class="btn btn-success">Добавить новости</button>
            </a>
            <br/>
            <br/>

        </div>
        <div class="col-md-12">
            <ul class="list-group">
                @foreach($news as $k)
                <li class="list-group-item list-img">

                    @if($k->image != null) <img  src="{{asset($k->image)}}" > @endif    {{$k->title}}

                    <div class="right flex">
                        <div>
                            <a href="{{route('news.edit',$k->id)}}">
                                <button type="button" class="btn btn-warning"> <span><i class="fas fa-edit"></i></span></button>

                            </a>
                        </div>
                        <div>
                            <form action="{{ route('news.destroy',$k->id) }}" onclick="return confirm('Вы действительно хотите удалить')" method="POST">

                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </div>

                    </div>
                </li>
                @endforeach
            </ul>
            <br/>
            {{$news->links()}}
        </div>

    </div>
@endsection

resources/views/admin/newsAdd.blade.php
@extends('layouts.admin')

@section('js')

    <script src="{{asset('ckeditor/ckeditor.js')}}"></script>
    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'text' );
    </script>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h2 class="news-h2">Добавить новости</h2>
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{route('news.store')}}" method="post" enctype="multipart/form-data"  >
                <div class="form-group">
                    <label>Тема</label>
                    <input type="text" name="title" class="form-control" required/>
                </div>
                <div class="form-group">
                    <label>Текст</label>
                    <textarea name="text" id="text" class="form-control" required></textarea>
                </div>
                <div class="form-group">
                    <label>Картинка</label>
                    <input type="file" name="image">
                </div>
                @csrf
                <button type="submit" class="btn btn-danger">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/newsEdit.blade.php
@extends('layouts.admin')

@section('js')

    <script src="{{asset('ckeditor/ckeditor.js')}}"></script>
    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'text' );
    </script>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h2 class="news-h2">Редактировать новости</h2>
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('news.update',$news->id) }}" method="post" enctype="multipart/form-data"  >
                <div class="form-group">
                    <label>Тема</label>
                    <input type="text" name="title" class="form-control" value="{{$news->title}}" required/>
                </div>
                <div class="form-group">
                    <label>Текст</label>
                    <textarea name="text" id="text" class="form-control" required>{{$news->text}}</textarea>
                </div>
                <div class="form-group">
                    <label>Картинка</label>
                    <input type="file" name="image">
                    <br/>
                    @if($news->image != null)
                        <div>
                            <img style="width: 100px" src="{{asset($news->image)}}">
                        </div>
                        @endif
                </div>
                @csrf
                @method('PUT')
                <button type="submit" class="btn btn-danger">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/certainNews.blade.php
@extends('layouts.header')

@section('content')

    <div class="container">
        <div class="row news-cont">

            <div class="col-md-12">
                <h1>{{$news->title}}</h1>

                @if($news->image !=  null)
                    <div class="one-image">
                        <img src="{{asset($news->image)}}"/>
                    </div>

                    @endif

                {!! $news->text !!}


            </div>


        </div>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ Session::token() }}">
    <title> Админка - Новости </title>
    <link href="{{asset('admin/vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/css/ruang-admin.min.css')}}" rel="stylesheet">
    <link href="{{asset('admin/css/adminStyle.css?v=1.5')}}" rel="stylesheet">
    <link href="{{asset('admin/js/jquery-ui.min.css')}}" rel="stylesheet">
    @yield('css')
</head>

<body id="page-top">

<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
            <div class="sidebar-brand-icon">

            </div>
            <div class="sidebar-brand-text mx-3">Новости-Админка</div>
        </a>
        <hr class="sidebar-divider my-0">
        <li class="nav-item active">
            <a class="nav-link" href="/">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Сайт</span></a>
        </li>
        <hr class="sidebar-divider">

        <div class="sidebar-heading">
            Разделы
        </div>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{{route('news.index')}}">
                <i class="fas fa-plus-circle"></i>  <span>Добавить новости</span>
            </a>

        </li>
        <hr class="sidebar-divider">

    </ul>

    <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">

            <!-- TopBar -->
            <nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
                <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <ul class="navbar-nav ml-auto">
                    <div class="topbar-divider d-none d-sm-block"></div>
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <img class="img-profile rounded-circle" src="{{asset('admin/img/boy.png')}}" style="max-width: 60px">
                            <span class="ml-2 d-none d-lg-inline text-white small">
                    {{Auth::user()->name}}


                </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">

                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> log out
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>

                        </div>
                    </li>
                </ul>
            </nav>
            <!-- Topbar -->


            <div class="container-fluid" id="container-wrapper">
                @yield('content')
            </div>

        </div>
        <!-- Scroll to top -->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
    </div>


</div>


<footer id="footer">
</footer>


<script src="{{asset('admin/vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('admin/js/jquery-ui.min.js')}}"></script>
<script src="{{asset('admin/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('admin/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
<script src="{{asset('admin/js/ruang-admin.js')}}"></script>
@yield('js')
<script src="{{asset('admin/js/workscript.js')}}"></script>



</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Новости
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">Вход</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">Регистрация</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no,shrink-to-fit=no">
    <meta name="csrf-token" content="{{ Session::token() }}">
    <title>Новости</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{{asset('css/style.css')}}" rel="stylesheet">

    @yield('css')
    @yield('meta')
</head>

<body id="page-top">

        <header>
            <div class="container header">
                <div class="row">
                    <div class="col-md-4 col-4">
                        <div class="logo-text">
                            <a href="/">
                                Новости
                            </a>
                        </div>
                    </div>
                    <div class="col-md-4 hide"></div>
                    <div class="col-md-4 col-8">
                        <div class="addButton">
                            <a href="{{route('news.index')}}">
                                <button type="button" class="btn btn-primary"> <i class="fas fa-plus"></i> Добавить новости</button>
                            </a>

                        </div>
                    </div>
                </div>
            </div>
        </header>

        @yield('content')

        <footer id="footer">

        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/f442ea367e.js"></script>



        @yield('js')
</body>

</html>

resources/views/main.blade.php
@extends('layouts.header')

@section('content')

    <div class="container">
        <div class="row">

            @foreach($news as $k)
                <div class="col-md-3">
                        <div class="card" style="width: 18rem; ">
                            @if($k->image != null)
                                <img src="{{asset($k->image)}}" class="card-img-top" alt="{{$k->title}}">
                            @endif
                            <div class="card-body">
                                <h5 class="card-title">{{$k->title}}</h5>

                                <a href="{{route('certainNews',$k->id)}}" class="btn btn-primary">Подробнее</a>
                            </div>
                        </div>
                </div>
            @endforeach


        </div>
    </div>

@endsection